/*
Cerinta 11: Crearea tabelelor în SQL și inserarea de date coerente în fiecare dintre acestea: 
   - minimum 5 înregistrări în fiecare tabel neasociativ; 
   - minimum 10 înregistrări în tabelele asociative; 
   - maxim 30 de înregistrări în fiecare tabel 
*/


-- CLEANUP
DROP TABLE executie_ordin CASCADE CONSTRAINTS;
DROP TABLE detinere_portofoliu CASCADE CONSTRAINTS;


-- simulare update pentru ordinele executate
UPDATE ordin SET status_ordin = 'EXECUTAT' WHERE id_ordin = 10;
UPDATE ordin SET status_ordin = 'EXECUTAT' WHERE id_ordin = 12;
UPDATE ordin SET status_ordin = 'EXECUTAT' WHERE id_ordin = 15;
UPDATE ordin SET status_ordin = 'EXECUTAT' WHERE id_ordin = 3;
UPDATE ordin SET status_ordin = 'EXECUTAT' WHERE id_ordin = 20;
UPDATE ordin SET status_ordin = 'EXECUTAT' WHERE id_ordin = 16;
COMMIT;

/*
- 11: **executie_ordin**
   - `id_executie` # (Primary Key)
   - `id_ordin` (Foreign Key -> ordin.id_ordin, NOT NULL)
   - `id_bursa` (Foreign Key -> bursa.id_bursa, NOT NULL)
   - `cantitate_executata` (NUMBER(14,4), NOT NULL, CHECK (cantitate_executata > 0))
   - `pret_executie` (NUMBER(14,4), NOT NULL, CHECK (pret_executie > 0))
   - `data_executie` (DATE, NOT NULL)
*/
CREATE TABLE executie_ordin (
   id_executie NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
   id_ordin NUMBER NOT NULL,
   id_bursa NUMBER NOT NULL,
   cantitate_executata NUMBER(14,4) NOT NULL CHECK (cantitate_executata > 0),
   pret_executie NUMBER(14,4) NOT NULL CHECK (pret_executie > 0),
   data_executie DATE NOT NULL,

   CONSTRAINT fk_executie_ordin_id_ordin
      FOREIGN KEY (id_ordin)
      REFERENCES ordin(id_ordin),

   CONSTRAINT fk_executie_ordin_id_bursa
      FOREIGN KEY (id_bursa)
      REFERENCES bursa(id_bursa)
);
DELETE FROM executie_ordin;
INSERT INTO executie_ordin (id_ordin, id_bursa, cantitate_executata, pret_executie, data_executie) VALUES (10, 2, 75.0, 177.16, TO_DATE('2026-02-20', 'YYYY-MM-DD'));
INSERT INTO executie_ordin (id_ordin, id_bursa, cantitate_executata, pret_executie, data_executie) VALUES (12, 8, 76.0, 352.767, TO_DATE('2026-04-28', 'YYYY-MM-DD '));
INSERT INTO executie_ordin (id_ordin, id_bursa, cantitate_executata, pret_executie, data_executie) VALUES (15, 11, 42.0, 36.1, TO_DATE('2026-02-05', 'YYYY-MM-DD'));
INSERT INTO executie_ordin (id_ordin, id_bursa, cantitate_executata, pret_executie, data_executie) VALUES (3, 1, 95.0, 40.76, TO_DATE('2026-04-09', 'YYYY-MM-DD'));
INSERT INTO executie_ordin (id_ordin, id_bursa, cantitate_executata, pret_executie, data_executie) VALUES (20, 2, 9.0, 258.762, TO_DATE('2026-01-15', 'YYYY-MM-DD'));
INSERT INTO executie_ordin (id_ordin, id_bursa, cantitate_executata, pret_executie, data_executie) VALUES (16, 11, 39.0, 36.1, TO_DATE('2026-03-10', 'YYYY-MM-DD'));
COMMIT;



/*
Tabel 08: **detinere_portofoliu** (*tabel asociativ*)
   - `id_portofoliu` (Foreign Key -> portofoliu.id_portofoliu)
   - `ticker` (Foreign Key -> simbol_bursier.ticker)
   - `cantitate` (NUMBER(14,4), NOT NULL, CHECK (cantitate >= 0))
   - `pret_mediu` (NUMBER(14,4), CHECK (pret_mediu >= 0))
   - `data_actualizare` (DATE, DEFAULT SYSDATE)
   - Primary Key compus: # (`id_portofoliu`, `ticker`)
*/

CREATE TABLE detinere_portofoliu (
   id_portofoliu NUMBER NOT NULL, -- portofoliu.id_portofoliu
   ticker VARCHAR2(10) NOT NULL, -- simbol_bursier.ticker
   cantitate NUMBER(14,4) NOT NULL CHECK (cantitate >= 0),
   pret_mediu NUMBER(14,4) NOT NULL CHECK (pret_mediu >= 0),
   data_actualizare DATE DEFAULT SYSDATE,

   -- primary key compus din id_portofoliu + ticker
   CONSTRAINT pk_detinere_portofoliu PRIMARY KEY (id_portofoliu, ticker),

   CONSTRAINT fk_detinere_portofoliu_id_portofoliu
      FOREIGN KEY (id_portofoliu)
      REFERENCES portofoliu (id_portofoliu),

   CONSTRAINT fk_detinere_portofoliu_ticker
      FOREIGN KEY (ticker)
      REFERENCES simbol_bursier (ticker)
);
DELETE FROM detinere_portofoliu;

COMMIT;