/*
Tablele care depind de faza 1 si 2

Cerinta 11: Crearea tabelelor în SQL și inserarea de date coerente în fiecare dintre acestea: 
   - minimum 5 înregistrări în fiecare tabel neasociativ; 
   - minimum 10 înregistrări în tabelele asociative; 
   - maxim 30 de înregistrări în fiecare tabel 
*/

-- CLEANUP:
DROP TABLE curs_valutar CASCADE CONSTRAINTS;
DROP TABLE ordin CASCADE CONSTRAINTS;
/*
- 03: **curs_valutar**
   - `id_curs` # (Primary Key)
   - `cod_moneda_sursa` (Foreign Key -> moneda.cod_moneda, NOT NULL, VARCHAR2(10))
   - `cod_moneda_dest` (Foreign Key -> moneda.cod_moneda, NOT NULL, VARCHAR2(10))
   - `data_curs` (DATE, NOT NULL)
   - `valoare_curs` (NUMBER(18,6), NOT NULL, CHECK (valoare_curs > 0))
   - Constrangere unica: (`cod_moneda_sursa`, `cod_moneda_dest`, `data_curs`)
*/
CREATE TABLE curs_valutar (
   id_curs NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   cod_moneda_sursa VARCHAR2(10) NOT NULL,
   cod_moneda_destinatie VARCHAR2(10) NOT NULL,
   data_curs DATE NOT NULL,
   valoare_curs NUMBER(18, 6) NOT NULL CHECK (valoare_curs > 0),

   CONSTRAINT fk_curs_moneda_sursa
      FOREIGN KEY (cod_moneda_sursa)
      REFERENCES moneda (cod_moneda),
   
   CONSTRAINT fk_curs_moneda_destinatie
      FOREIGN KEY (cod_moneda_destinatie)
      REFERENCES moneda (cod_moneda)
);
DELETE FROM curs_valutar;
INSERT INTO curs_valutar (cod_moneda_sursa, cod_moneda_destinatie, data_curs, valoare_curs) VALUES ('DKK', 'CHF', TO_DATE('2026-05-18', 'YYYY-MM-DD'), 0.1223360002040863);
INSERT INTO curs_valutar (cod_moneda_sursa, cod_moneda_destinatie, data_curs, valoare_curs) VALUES ('KRW', 'CNY', TO_DATE('2026-05-18', 'YYYY-MM-DD'), 0.004544000141322613);
INSERT INTO curs_valutar (cod_moneda_sursa, cod_moneda_destinatie, data_curs, valoare_curs) VALUES ('JPY', 'DKK', TO_DATE('2026-05-18', 'YYYY-MM-DD'), 0.04030900076031685);
INSERT INTO curs_valutar (cod_moneda_sursa, cod_moneda_destinatie, data_curs, valoare_curs) VALUES ('CNY', 'EUR', TO_DATE('2026-05-11', 'YYYY-MM-DD'), 0.12495800107717514);
INSERT INTO curs_valutar (cod_moneda_sursa, cod_moneda_destinatie, data_curs, valoare_curs) VALUES ('USD', 'GBP', TO_DATE('2026-05-16', 'YYYY-MM-DD'), 0.746749997138977);
INSERT INTO curs_valutar (cod_moneda_sursa, cod_moneda_destinatie, data_curs, valoare_curs) VALUES ('TWD', 'JPY', TO_DATE('2026-05-10', 'YYYY-MM-DD'), 4.995751857757568);
INSERT INTO curs_valutar (cod_moneda_sursa, cod_moneda_destinatie, data_curs, valoare_curs) VALUES ('CHF', 'KRW', TO_DATE('2026-05-02', 'YYYY-MM-DD'), 1885.8875732421875);
INSERT INTO curs_valutar (cod_moneda_sursa, cod_moneda_destinatie, data_curs, valoare_curs) VALUES ('GBP', 'RON', TO_DATE('2026-05-13', 'YYYY-MM-DD'), 5.993503093719482);
INSERT INTO curs_valutar (cod_moneda_sursa, cod_moneda_destinatie, data_curs, valoare_curs) VALUES ('EUR', 'TWD', TO_DATE('2026-05-10', 'YYYY-MM-DD'), 36.808895111083984);
INSERT INTO curs_valutar (cod_moneda_sursa, cod_moneda_destinatie, data_curs, valoare_curs) VALUES ('RON', 'USD', TO_DATE('2026-05-18', 'YYYY-MM-DD'), 0.22329901158809662);
COMMIT;


/*
- 10: **ordin**
   - `id_ordin` # (Primary Key)
   - `id_portofoliu` (Foreign Key -> portofoliu.id_portofoliu, NOT NULL)
   - `ticker` (Foreign Key -> simbol_bursier.ticker, NOT NULL)
   - `tip_sens` (VARCHAR2(10), CHECK (tip_sens IN ('CUMPARARE','VANZARE')))
   - `tip_ordin` (VARCHAR2(10), CHECK (tip_ordin IN ('PIATA','LIMITA')))
   - `cantitate` (NUMBER(14,4), NOT NULL, CHECK (cantitate > 0))
   - `pret_limita` (NUMBER(14,4))
   - `data_ordin` (DATE, DEFAULT SYSDATE)
   - `status_ordin` (VARCHAR2(10), DEFAULT 'NOU', CHECK (status_ordin IN ('NOU','PARTIAL','EXECUTAT','ANULAT')))
*/
CREATE TABLE ordin (
   id_ordin NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   id_portofoliu NUMBER NOT NULL,
   ticker VARCHAR2(10) NOT NULL,
   tip_sens VARCHAR2(10) CHECK (tip_sens IN ('CUMPARARE','VANZARE')),
   tip_ordin VARCHAR2(10) CHECK (tip_ordin IN ('PIATA','LIMITA')),
   cantitate NUMBER(14,4) NOT NULL CHECK (cantitate > 0),
   pret_limita NUMBER(14,4),
   data_ordin DATE DEFAULT SYSDATE,
   status_ordin VARCHAR2(10) DEFAULT 'NOU' CHECK (status_ordin IN ('NOU','PARTIAL','EXECUTAT','ANULAT')),

   CONSTRAINT fk_ordin_portofoliu
      FOREIGN KEY (id_portofoliu)
      REFERENCES portofoliu (id_portofoliu),

   CONSTRAINT fk_ordin_ticker
      FOREIGN KEY (ticker)
      REFERENCES simbol_bursier (ticker)

);
DELETE FROM ordin;
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (1, 'NVDA', 'CUMPARARE', 'PIATA', 51, 288.32717364308235, TO_DATE('2026-03-16', 'YYYY-MM-DD'), 'NOU');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (1, 'NVDA', 'VANZARE', 'LIMITA', 83, 171.1970062482055, TO_DATE('2026-01-27', 'YYYY-MM-DD'), 'NOU');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (1, 'NVDA', 'VANZARE', 'LIMITA', 23, 185.05520880322658, TO_DATE('2026-04-04', 'YYYY-MM-DD'), 'NOU');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (1, 'NVDA', 'VANZARE', 'LIMITA', 78, 196.47986526409048, TO_DATE('2026-03-14', 'YYYY-MM-DD'), 'NOU');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (1, 'NVDA', 'VANZARE', 'PIATA', 21, 39.25746501197327, TO_DATE('2026-02-11', 'YYYY-MM-DD'), 'NOU');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (3, 'NVO', 'CUMPARARE', 'PIATA', 33, 43.12153211249824, TO_DATE('2026-04-16', 'YYYY-MM-DD'), 'NOU');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (2, 'AAPL', 'CUMPARARE', 'LIMITA', 38, 294.1394725023777, TO_DATE('2026-03-23', 'YYYY-MM-DD'), 'EXECUTAT');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (1, 'NVDA', 'VANZARE', 'LIMITA', 19, 206.52338110707583, TO_DATE('2026-03-26', 'YYYY-MM-DD'), 'NOU');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (1, 'ALV', 'CUMPARARE', 'PIATA', 37, 383.4355818082464, TO_DATE('2026-04-14', 'YYYY-MM-DD'), 'NOU');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (3, 'AAPL', 'CUMPARARE', 'LIMITA', 85, 262.06751236485326, TO_DATE('2026-01-22', 'YYYY-MM-DD'), 'ANULAT');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (5, 'TLV', 'VANZARE', 'LIMITA', 87, 38.232252891187514, TO_DATE('2026-03-01', 'YYYY-MM-DD'), 'NOU');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (5, 'ALV', 'CUMPARARE', 'LIMITA', 21, 372.6692427139335, TO_DATE('2026-02-09', 'YYYY-MM-DD'), 'NOU');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (2, 'TLV', 'CUMPARARE', 'PIATA', 37, 35.72310696983276, TO_DATE('2026-02-17', 'YYYY-MM-DD'), 'NOU');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (4, 'NVO', 'VANZARE', 'LIMITA', 96, 42.244149697955876, TO_DATE('2026-02-28', 'YYYY-MM-DD'), 'NOU');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (5, 'NVO', 'CUMPARARE', 'PIATA', 28, 39.57702074955693, TO_DATE('2026-01-07', 'YYYY-MM-DD'), 'NOU');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (2, 'ALV', 'CUMPARARE', 'LIMITA', 78, 361.709494868684, TO_DATE('2026-04-24', 'YYYY-MM-DD'), 'EXECUTAT');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (1, 'NVO', 'CUMPARARE', 'PIATA', 72, 44.89399037575808, TO_DATE('2026-01-17', 'YYYY-MM-DD'), 'NOU');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (3, 'ALV', 'CUMPARARE', 'PIATA', 91, 385.0662713370273, TO_DATE('2026-03-10', 'YYYY-MM-DD'), 'EXECUTAT');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (1, 'TLV', 'VANZARE', 'PIATA', 46, 38.323314882863414, TO_DATE('2026-02-11', 'YYYY-MM-DD'), 'EXECUTAT');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (2, 'NVO', 'VANZARE', 'PIATA', 90, 45.363646887781485, TO_DATE('2026-02-07', 'YYYY-MM-DD'), 'EXECUTAT');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (4, 'ALV', 'CUMPARARE', 'LIMITA', 52, 372.7093006774231, TO_DATE('2026-02-18', 'YYYY-MM-DD'), 'PARTIAL');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (4, 'AAPL', 'CUMPARARE', 'PIATA', 55, 262.2876553779286, TO_DATE('2026-01-01', 'YYYY-MM-DD'), 'ANULAT');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (1, 'AAPL', 'CUMPARARE', 'LIMITA', 2, 257.9711771023666, TO_DATE('2026-04-26', 'YYYY-MM-DD'), 'NOU');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (3, 'TLV', 'VANZARE', 'LIMITA', 77, 40.21636178607008, TO_DATE('2026-03-22', 'YYYY-MM-DD'), 'NOU');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (5, 'NVDA', 'VANZARE', 'PIATA', 37, 171.04024307670875, TO_DATE('2026-01-10', 'YYYY-MM-DD'), 'NOU');
COMMIT;
