/*
Tablele care depind de faza 1 si 2

Cerinta 11: Crearea tabelelor în SQL și inserarea de date coerente în fiecare dintre acestea: 
   - minimum 5 înregistrări în fiecare tabel neasociativ; 
   - minimum 10 înregistrări în tabelele asociative; 
   - maxim 30 de înregistrări în fiecare tabel 
*/

-- CLEANUP:
DROP TABLE curs_valutar CASCADE CONSTRAINTS;
DROP TABLE ordin CASCADE CONSTRAINTS;
/*
- 03: **curs_valutar**
   - `id_curs` # (Primary Key)
   - `cod_moneda_sursa` (Foreign Key -> moneda.cod_moneda, NOT NULL, VARCHAR2(10))
   - `cod_moneda_dest` (Foreign Key -> moneda.cod_moneda, NOT NULL, VARCHAR2(10))
   - `data_curs` (DATE, NOT NULL)
   - `valoare_curs` (NUMBER(18,6), NOT NULL, CHECK (valoare_curs > 0))
   - Constrangere unica: (`cod_moneda_sursa`, `cod_moneda_dest`, `data_curs`)
*/
CREATE TABLE curs_valutar (
   id_curs NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   cod_moneda_sursa VARCHAR2(10) NOT NULL,
   cod_moneda_destinatie VARCHAR2(10) NOT NULL,
   data_curs DATE NOT NULL,
   valoare_curs NUMBER(18, 6) NOT NULL CHECK (valoare_curs > 0),

   CONSTRAINT fk_curs_moneda_sursa
      FOREIGN KEY (cod_moneda_sursa)
      REFERENCES moneda (cod_moneda),
   
   CONSTRAINT fk_curs_moneda_destinatie
      FOREIGN KEY (cod_moneda_destinatie)
      REFERENCES moneda (cod_moneda)
);
DELETE FROM curs_valutar;
INSERT INTO curs_valutar (cod_moneda_sursa, cod_moneda_destinatie, data_curs, valoare_curs) VALUES ('DKK', 'CHF', TO_DATE('2026-05-18', 'YYYY-MM-DD'), 0.1223360002040863);
INSERT INTO curs_valutar (cod_moneda_sursa, cod_moneda_destinatie, data_curs, valoare_curs) VALUES ('KRW', 'CNY', TO_DATE('2026-05-18', 'YYYY-MM-DD'), 0.004544000141322613);
INSERT INTO curs_valutar (cod_moneda_sursa, cod_moneda_destinatie, data_curs, valoare_curs) VALUES ('JPY', 'DKK', TO_DATE('2026-05-18', 'YYYY-MM-DD'), 0.04030900076031685);
INSERT INTO curs_valutar (cod_moneda_sursa, cod_moneda_destinatie, data_curs, valoare_curs) VALUES ('CNY', 'EUR', TO_DATE('2026-05-11', 'YYYY-MM-DD'), 0.12495800107717514);
INSERT INTO curs_valutar (cod_moneda_sursa, cod_moneda_destinatie, data_curs, valoare_curs) VALUES ('USD', 'GBP', TO_DATE('2026-05-16', 'YYYY-MM-DD'), 0.746749997138977);
INSERT INTO curs_valutar (cod_moneda_sursa, cod_moneda_destinatie, data_curs, valoare_curs) VALUES ('TWD', 'JPY', TO_DATE('2026-05-10', 'YYYY-MM-DD'), 4.995751857757568);
INSERT INTO curs_valutar (cod_moneda_sursa, cod_moneda_destinatie, data_curs, valoare_curs) VALUES ('CHF', 'KRW', TO_DATE('2026-05-02', 'YYYY-MM-DD'), 1885.8875732421875);
INSERT INTO curs_valutar (cod_moneda_sursa, cod_moneda_destinatie, data_curs, valoare_curs) VALUES ('GBP', 'RON', TO_DATE('2026-05-13', 'YYYY-MM-DD'), 5.993503093719482);
INSERT INTO curs_valutar (cod_moneda_sursa, cod_moneda_destinatie, data_curs, valoare_curs) VALUES ('EUR', 'TWD', TO_DATE('2026-05-10', 'YYYY-MM-DD'), 36.808895111083984);
INSERT INTO curs_valutar (cod_moneda_sursa, cod_moneda_destinatie, data_curs, valoare_curs) VALUES ('RON', 'USD', TO_DATE('2026-05-18', 'YYYY-MM-DD'), 0.22329901158809662);
COMMIT;


/*
- 10: **ordin**
   - `id_ordin` # (Primary Key)
   - `id_portofoliu` (Foreign Key -> portofoliu.id_portofoliu, NOT NULL)
   - `ticker` (Foreign Key -> simbol_bursier.ticker, NOT NULL)
   - `tip_sens` (VARCHAR2(10), CHECK (tip_sens IN ('CUMPARARE','VANZARE')))
   - `tip_ordin` (VARCHAR2(10), CHECK (tip_ordin IN ('PIATA','LIMITA')))
   - `cantitate` (NUMBER(14,4), NOT NULL, CHECK (cantitate > 0))
   - `pret_limita` (NUMBER(14,4))
   - `data_ordin` (DATE, DEFAULT SYSDATE)
   - `status_ordin` (VARCHAR2(10), DEFAULT 'NOU', CHECK (status_ordin IN ('NOU','PARTIAL','EXECUTAT','ANULAT')))
*/
CREATE TABLE ordin (
   id_ordin NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   id_portofoliu NUMBER NOT NULL,
   ticker VARCHAR2(10) NOT NULL,
   tip_sens VARCHAR2(10) CHECK (tip_sens IN ('CUMPARARE','VANZARE')),
   tip_ordin VARCHAR2(10) CHECK (tip_ordin IN ('PIATA','LIMITA')),
   cantitate NUMBER(14,4) NOT NULL CHECK (cantitate > 0),
   pret_limita NUMBER(14,4),
   data_ordin DATE DEFAULT SYSDATE,
   status_ordin VARCHAR2(10) DEFAULT 'NOU' CHECK (status_ordin IN ('NOU','PARTIAL','EXECUTAT','ANULAT')),

   CONSTRAINT fk_ordin_portofoliu
      FOREIGN KEY (id_portofoliu)
      REFERENCES portofoliu (id_portofoliu),

   CONSTRAINT fk_ordin_ticker
      FOREIGN KEY (ticker)
      REFERENCES simbol_bursier (ticker)

);
DELETE FROM ordin;
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (4, 'AAPL', 'VANZARE', 'LIMITA', 26, 305.67967715415267, TO_DATE('2026-04-07', 'YYYY-MM-DD'), 'PARTIAL');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (2, 'TLV', 'VANZARE', 'LIMITA', 48, 37.152962356972665, TO_DATE('2026-02-28', 'YYYY-MM-DD'), 'NOU');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (2, 'AAPL', 'CUMPARARE', 'PIATA', 64, 270.9538216058397, TO_DATE('2026-03-13', 'YYYY-MM-DD'), 'NOU');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (5, 'TLV', 'VANZARE', 'PIATA', 97, 37.65137212137308, TO_DATE('2026-01-01', 'YYYY-MM-DD'), 'PARTIAL');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (1, 'ALV', 'VANZARE', 'PIATA', 69, 375.9760303753835, TO_DATE('2026-03-08', 'YYYY-MM-DD'), 'NOU');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (2, 'NVO', 'VANZARE', 'LIMITA', 33, 42.84663233546247, TO_DATE('2026-03-03', 'YYYY-MM-DD'), 'PARTIAL');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (3, 'NVO', 'VANZARE', 'PIATA', 65, 40.59609118924823, TO_DATE('2026-01-05', 'YYYY-MM-DD'), 'EXECUTAT');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (1, 'NVO', 'VANZARE', 'PIATA', 61, 45.47565754680649, TO_DATE('2026-01-22', 'YYYY-MM-DD'), 'NOU');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (3, 'ALV', 'VANZARE', 'PIATA', 97, 336.41396460151236, TO_DATE('2026-03-28', 'YYYY-MM-DD'), 'PARTIAL');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (3, 'AAPL', 'VANZARE', 'PIATA', 22, 247.60289718128823, TO_DATE('2026-01-21', 'YYYY-MM-DD'), 'NOU');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (4, 'NVO', 'VANZARE', 'PIATA', 9, 46.84895019023342, TO_DATE('2026-04-05', 'YYYY-MM-DD'), 'NOU');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (1, 'NVDA', 'CUMPARARE', 'LIMITA', 94, 181.93651680493448, TO_DATE('2026-03-23', 'YYYY-MM-DD'), 'ANULAT');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (2, 'ALV', 'CUMPARARE', 'LIMITA', 7, 370.2751159311981, TO_DATE('2026-04-10', 'YYYY-MM-DD'), 'ANULAT');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (5, 'NVDA', 'CUMPARARE', 'LIMITA', 3, 218.77771869519628, TO_DATE('2026-01-11', 'YYYY-MM-DD'), 'NOU');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (1, 'TLV', 'CUMPARARE', 'PIATA', 36, 34.29996657142006, TO_DATE('2026-03-15', 'YYYY-MM-DD'), 'ANULAT');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (1, 'AAPL', 'CUMPARARE', 'LIMITA', 58, 262.5065538277112, TO_DATE('2026-03-28', 'YYYY-MM-DD'), 'NOU');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (5, 'AAPL', 'CUMPARARE', 'PIATA', 46, 251.63915162699894, TO_DATE('2026-02-05', 'YYYY-MM-DD'), 'EXECUTAT');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (5, 'ALV', 'VANZARE', 'LIMITA', 46, 367.7178450710641, TO_DATE('2026-04-02', 'YYYY-MM-DD'), 'EXECUTAT');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (3, 'TLV', 'CUMPARARE', 'LIMITA', 82, 38.776280304644565, TO_DATE('2026-04-05', 'YYYY-MM-DD'), 'PARTIAL');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (2, 'NVDA', 'VANZARE', 'LIMITA', 63, 179.2382627301148, TO_DATE('2026-03-16', 'YYYY-MM-DD'), 'EXECUTAT');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (5, 'NVO', 'VANZARE', 'LIMITA', 92, 43.240585103414894, TO_DATE('2026-03-27', 'YYYY-MM-DD'), 'NOU');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (4, 'NVDA', 'CUMPARARE', 'PIATA', 69, 199.8731226215731, TO_DATE('2026-03-22', 'YYYY-MM-DD'), 'NOU');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (4, 'ALV', 'VANZARE', 'LIMITA', 13, 391.16210048446743, TO_DATE('2026-03-03', 'YYYY-MM-DD'), 'EXECUTAT');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (4, 'TLV', 'CUMPARARE', 'LIMITA', 54, 36.99275204433293, TO_DATE('2026-01-09', 'YYYY-MM-DD'), 'EXECUTAT');
INSERT INTO ordin (id_portofoliu, ticker, tip_sens, tip_ordin, cantitate, pret_limita, data_ordin, status_ordin) VALUES (3, 'NVDA', 'VANZARE', 'PIATA', 50, 208.24301340090284, TO_DATE('2026-04-06', 'YYYY-MM-DD'), 'NOU');
COMMIT;
